import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Home from "./page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><div>
      {/* Navbar */}
      <div className="bg-[#437993] p-[16px] flex justify-center">
     
        <div className="max-w-[1200px]   w-full flex flex-col ">
          <h1 className="font-bold max-w-[396px] w-full text-white text-[2.25rem] leading-[2.5rem]">
            Notes App
          </h1>
          <p className="font-light max-w-[396px] w-full text-white">
            Take Notes and never forget
          </p>
        </div>
          </div>
        </div>
        
        {children} 
      
      </body>
    </html>
  );
}
